App gui merge to main
VERDORIEBOND/Wine_Cellar_Manager pull request #3
Opened 2021-12-02 13:37 UTC by VERDORIEBOND

2021-12-02 13:45 UTC, DavidEertink approved these changes

2021-12-02 21:52 UTC, lepel100 requested changes
Hi, weet niet zeker of deze PR al klaar was voor review of dat je er nog mee bezig was, heb een paar kleine puntjes aangestipt. Verder ziet het er goed uit!

2021-12-02 21:52 UTC, lepel100 commented on WineCellar/WineCellar.GUI/appsettings.json
> +    "DefaultConnection": "Data Source=127.0.0.1;Initial Catalog=WineDB;User ID=sa;Password=WineCellar21!;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;Mult
Dit lijkt me een foutje, misschien moeten we even een gitignore maken voor de appsettings?

2021-12-02 21:52 UTC, lepel100 commented on WineCellar/WineCellar.GUI/MainWindow.xaml.cs
> +
2 keer een lege foreach?

2021-12-02 21:52 UTC, lepel100 commented on WineCellar/WineCellar.GUI/MainWindow.xaml.cs
> +                Debug.Print(VARIABLE.Name);
Dient deze debug function nog ergens voor in de production versie?

2021-12-02 21:52 UTC, lepel100 commented on WineCellar/WineCellar.GUI/MainWindow.xaml.cs
> +            //var items = Controller.Data.GetWineData();
Comments zou ik ook weghalen

2021-12-03 09:22 UTC, lepel100 approved these changes
Top man

2021-12-03 09:24 UTC, merged

2021-12-03 09:26 UTC, MonkeyOS approved these changes

2021-12-03 09:26 UTC, MonkeyOS commented on WineCellar/WineCellar.Controller/WineCellar.Controller.csproj
> +        <LangVersion>preview</LangVersion>
Is dit 10 --> preview essentieel?